config/routes.rb
Project::Application.routes.draw do
  root :to => "users#view"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"
  get "user_view" => "users#view", :as => "user_view"

  controller :tasks, path: 'task' do
    get '/' => :index, as: :tasks
    post '/' => :create
    get 'new' => :new, as: :task_new
    get 'edit/:id' => :edit, as: :task_edit
    put '/:id' => :update
    get '/:id' => :show, as: :task_show
    get 'show_users/:id' => :show_users_task, as: :show_users_task
    delete 'add_users/:id_user/:id_task' => :delete_users, as: :task_user_delete
    put 'add_users/:id_task' => :create_users_for_task, as: :task_user_create
    delete ':id' => :destroy, as: :task_delete
    get 'type/:all' => :view_all_tasks, as: :view_all_tasks
  end

  resources :sessions do
    resources :users
  end

  resources :users do
    resources :tasks
  end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  belongs_to :user
  belongs_to :task
  attr_accessible :note, :role_id, :task_id, :user_id
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :journals
  has_many :users, through: :journals
  attr_accessible :date_end, :date_start, :name, :text

  validates :name, presence: true
  validates :text, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :journals
  has_many :tasks, through: :journals
attr_accessible :email, :fname, :lname, :login, :password, :password_confirmation
attr_accessor :password
before_save :encrypt_password

validates :fname, presence: true
validates :lname, presence: true
validates :login, presence: true, uniqueness: true
validates :email, presence: true, uniqueness: true
validates :password, presence: true, confirmation: true, :on => :create


def self.authenticate(inp_user, password)
  user = find_by_email(inp_user)
  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
  else
    user = find_by_login(inp_user)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

def encrypt_password
  if password.present?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout "login"
  def new
  end

  def create
    user = User.authenticate(params[:inp_user], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to user_view_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  helper_method :sort_column, :sort_direction, :task_users_column, :sort_direction_for_users
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      current_user.tasks << @task
      redirect_to tasks_path, :notice => "Complited"
    else
      render "new"
    end
  end

  def edit
    if @task = current_user.tasks.find_by_id(params[:id])
      @old_user = @task.users
      render "new"
    else
      redirect_to tasks_path
    end

  end

  def update
    @task = current_user.tasks.find_by_id(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to tasks_path, :notice => "Successfully updated task."
    else
      render "new"
    end
  end


  def destroy
    task = current_user.tasks.find_by_id(params[:id])
    if @d = task.destroy
      flash[:success] = "Task '#{task.name}' deleted"
    else
      redirect_to @d
    end
    redirect_to tasks_path
  end

  def index
   @task = current_user.tasks.order("#{sort_column} #{sort_direction}").paginate(:per_page => 20, :page => params[:page])
  end

  def show
   if @task = Task.find_by_id(params[:id])
     @old_user = @task.users
   else
     redirect_to tasks_path
   end
  end

  def show_users_task
    if @task = current_user.tasks.find_by_id(params[:id])
      @old_user = @task.users.order("#{task_users_column} #{sort_direction}").paginate(:per_page => 20, :page => params[:page])
    else
      redirect_to tasks_path
    end
  end

  def delete_users
    j = Journal.where(user_id: params[:id_user]).where(task_id: params[:id_task]).first
    flash[:success] = "User destroy" if j.destroy
    redirect_to show_users_task_path(params[:id_task])
  end

  def create_users_for_task
    j = Journal.where(user_id: params[:id]).where(task_id: params[:id_task]).first
    if j
      flash[:alert] = "Sorry. The task there is"
    else
      if User.find_by_id(params[:id])
        flash[:success] = "User add" if Journal.new(user_id: params[:id], task_id: params[:id_task]).save
      else
        flash[:alert] = "No search user"
      end
    end
    redirect_to show_users_task_path(params[:id_task])
  end

  def view_all_tasks
    @task = Task.order("#{sort_column} #{sort_direction}").paginate(:per_page => 20, :page => params[:page])
    @task.map do |el|
      users = Journal.where(task_id: el[:id])
       users.map do |em|
          em[:name] = User.find(em.user_id)
       end
      if (sort_direction_for_users=="asc")
        el[:users] = users.sort_by{|k, v| k}
      else
        el[:users] = users.sort_by{|k, v| k}.reverse
      end
    end

  end

  private

  def sort_column
      Task.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def task_users_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "fname"
  end

  def sort_direction
       %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_direction_for_users
    %w[asc desc].include?(params[:direction_users]) ? params[:direction_users] : "asc"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def view
    @user = User.where(id: session[:user_id]).first
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_view_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

  def sortable_task_users(column, title = nil)
    title ||= column.titleize
    css_class = column == task_users_column ? "current #{sort_direction}" : nil
    direction = column == task_users_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end

  def sortable_name_users(column, title = nil)
    title ||= column.titleize
    css_class = column == task_users_column ? "current #{sort_direction_for_users}" : nil
    direction_users = sort_direction_for_users == "asc" ? "desc" : "asc"
    link_to title, { :direction_users => direction_users}, {:class => css_class}
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
      <div class="login">
        Profile: <%= current_user.fname %>.
        <%= link_to "Log out", log_out_path %>
      </div>
      <div class="menu_profile">
        <%= link_to "Profile", user_view_path %>
        <%= link_to "My Task", tasks_path %>
      </div>
  <% else %>
      <div class="login">
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
      </div>
  <% end %>
</div>
<%= yield %>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if !current_user %>
      <div class="login">
        <%= link_to "Sign up", sign_up_path %> or
        <%= link_to "log in", log_in_path %>
      </div>
  <% end %>
</div>
<%= yield %>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
</body>
</html>

app/views/tasks/_index.html.erb
 <% if @task %>
  <table class="table_task">
    <tr class="sort">
      <th>№</th>
      <th><%= sortable "name" ,"Name"%></th>
      <th><%= sortable "date_start" ,"Date start"%></th>
      <th><%= sortable "date_end" ,"Date_end" %></th>
    </tr>
    <% i=0 %>
    <% @task.each { |t| %>
        <tr>
          <td>
            <%= i+=1 %>
          </td>
          <td>
            <%=  t.name %>
          </td>
          <td>
            <%=  t.date_start %>
          </td>
          <td>
            <%=  t.date_end %>
          </td>
          <td>
            <%= link_to "Show", task_show_path(t.id) %>
          </td>
          <td>
            <%= link_to "Edit", task_edit_path(t.id) %>
          </td>
          <td>
            <%= link_to "Add users for this task", show_users_task_path(t.id) %>
          </td>
          <td>
            <%= link_to "Delete", task_delete_path(t.id), method: :delete %>
          </td>
        </tr>
    <% } %>
  </table>
  <%= will_paginate @task %>
<% else %>
    <h2>No tasks!</h2>
<% end %>

app/views/tasks/_show_users_task.html.erb
<% if @old_user %>
    <table class="table_user_task">
      <tr class="sort">
        <th>№</th>
        <th><%= sortable_task_users "fname" ,"FName"%></th>
        <th><%= sortable_task_users "lname" ,"Lname"%></th>
        <th><%= sortable_task_users "email" ,"E-mail" %></th>
      </tr>
      <% i=0 %>
      <% @old_user.each { |t| %>
          <tr>
            <td>
              <%= i+=1 %>
            </td>
            <td>
              <%=  t.fname %>
            </td>
            <td>
              <%=  t.lname %>
            </td>
            <td>
              <%=  t.email %>
            </td>
            <td>
              <%= link_to "Delete", task_user_delete_path(t.id,@task.id), method: :delete %>
            </td>
          </tr>
      <% } %>
    </table>
<% else%>
    No users!
<% end%>

app/views/tasks/_view_all_tasks.html.erb
<% if @task %>
    <table class="table_task">
      <tr class="sort">
        <th>№</th>
        <th><%= sortable "name" ,"Name"%></th>
        <th><%= sortable "date_start" ,"Date start"%></th>
        <th><%= sortable "date_end" ,"Date_end" %></th>
        <th><%= sortable_name_users "fname" ,"Name_users" %></th>
      </tr>
      <% i=0 %>
      <% @task.each { |t| %>
          <tr>
            <td>
              <%= i+=1 %>
            </td>
            <td>
              <%=  t.name %>
            </td>
            <td>
              <%=  t.date_start %>
            </td>
            <td>
              <%=  t.date_end %>
            </td>
            <td>
              <%
                 t[:users].each { |user| %>
                  <p style="font-size: 8pt;color:green">
                    <%=  user[:name].fname + " " + user[:name].lname %>
                  </p>
              <% } %>
            </td>
            <td>
              <%= link_to "Show", task_show_path(t.id) %>
            </td>
          </tr>
      <% } %>
    </table>
    <%= will_paginate @task %>
<% else %>
    <h2>No tasks!</h2>
<% end %>

app/views/tasks/index.html.erb
<div class="menu_tasks">
  <%= link_to "View all tasks", view_all_tasks_path('all') %>
  <%= link_to "New", task_new_path %>
</div>
</div>
<h1>My tasks</h1>
<div id="view_content">
  <%= render 'index' %>
</div>

app/views/tasks/index.js.erb
$("#view_content").html("<%= escape_javascript(render 'index') %>");
$( ".table_task tr td a" ).button();

app/views/tasks/new.html.erb
<div>
<%= form_for @task, :url => tasks_path+"/"+@task.id.to_s do |f| %>
    <% if @task.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @task.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :text %><br />
      <%= f.text_area :text, :cols => "30", :rows => "10"  %>
    </p>
    <p>
      <%= f.label :date_start %><br />
      <%= f.text_field :date_start, class: "datepicker" %>
    </p>
    <p>
      <%= f.label :date_end %><br />
      <%= f.text_field :date_end, class: "datepicker" %>
    </p>

      <% if @old_user %>
        <p style="border-bottom: solid gray 2px; width:250px">
           Access user: <br>
        <p>
        <% @old_user.each do |user,key| %>
          <%= user.fname + " " + user.lname%>
          <br>
        <% end %>
      <% end %>
    </p>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>
</div>

app/views/tasks/show.html.erb
<p>
  <h2>
    Name task: <%= @task.name %>
  </h2>
</p>
<p>
  Text task: <%= @task.text %>
</p>
<p>
  Start date: <%= @task.date_start %>
</p>
<p>
  End date: <%= @task.date_end %>
</p>

<% if @old_user %>
    <p style="border-bottom: solid gray 2px; width:250px">
      Access user: <br>
    <p>
      <% @old_user.each do |user,key| %>
          <%= user.fname + " " + user.lname%>
          <br>
      <% end %>
<% end %>

app/views/tasks/show_users_task.html.erb
<p>
<H2>Task: <%= @task.name %> <br></H2>
</p>
<p>
  Access users: <br>
</p>
<div id="view_content_ajax">
  <%= render 'show_users_task' %>
</div>
<%= form_for @task, :url => task_user_create_path(@task.id) do |f| %>
    <p>
        <%= label_tag(:id, "Add id user") %>
        <%= text_field_tag(:id) %>
        <%= submit_tag("Add") %>
    </p>
<% end %>

app/views/tasks/show_users_task.js.erb
$("#view_content_ajax").html("<%= escape_javascript(render 'show_users_task') %>");
$( ".table_user_task tr td a" ).button();

app/views/tasks/view_all_tasks.html.erb
<div class="menu_tasks">
  <%= link_to "View all tasks", view_all_tasks_path %>
  <%= link_to "New", task_new_path %>
</div>
</div>
<h1>All tasks</h1>
<div id="view_content_all_tasks">
  <%= render 'view_all_tasks' %>
</div>

app/views/tasks/view_all_tasks.js.erb
$("#view_content_all_tasks").html("<%= escape_javascript(render 'view_all_tasks') %>");
$( ".table_task tr td a" ).button();

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :fname %><br />
      <%= f.text_field :fname %>
    </p>
    <p>
      <%= f.label :lname %><br />
      <%= f.text_field :lname %>
    </p>
    <p>
      <%= f.label :login %><br />
      <%= f.text_field :login %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>